dateModified: 1619188987
email:
  fromEmail: developer@gotobig.com
  fromName: 'Craft Starter'
  transportType: craft\mail\transportadapters\Sendmail
graphql:
  publicToken:
    enabled: false
    expiryDate: null
plugins:
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  dospaces:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  mix:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      assetPath: /
      publicPath: web
  neo:
    edition: standard
    enabled: true
    licenseKey: 3W7HCF8TID25XOX4F1AQ18UX
    schemaVersion: 2.8.16
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: 083PTPRKKCLTORQIO3M1ONCS
    schemaVersion: 3.0.9
  twigpack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'Craft Starter'
  schemaVersion: 3.6.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
