dateModified: 1622836456
email:
  fromEmail: developer@gotobig.com
  fromName: 'Craft Starter'
  transportType: craft\mail\transportadapters\Sendmail
graphql:
  publicToken:
    enabled: false
    expiryDate: null
plugins:
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  dospaces:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  image-toolbox:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  mix:
    edition: standard
    enabled: false
    schemaVersion: 1.0.0
    settings:
      assetPath: /
      publicPath: web
  neo:
    edition: standard
    enabled: true
    licenseKey: CF668M5WB7QZOVDZSCLR7WNE
    schemaVersion: 2.9.11
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: E1JKGK04EU4L7KNFTND8DZ5U
    schemaVersion: 3.0.9
  twigpack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'Craft Starter'
  schemaVersion: 3.6.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
